version: "3"
services:
  error-handling:
    container_name: error-handling
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        tag: ContainerName="{{.Name}}"
    volumes:
      - /var/lib/docker/error-handling
  logagent:
    image: "sematext/logagent:latest"
    environment:
      - LOGS_TOKEN=${LOGS_TOKEN}
      - LOGS_RECEIVER_URL="https://logsene-receiver.sematext.com"
      - MATCH_BY_NAME=.*error-handling.*
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
