module.exports = {
  moduleNameMapper: {
    "@server/(.*)": "<rootDir>/$1",
  },
  moduleFileExtensions: [
    "js",
    "mjs",
    "jsx",
    "vue",
    "ts",
    "tsx",
    "css",
    "less",
    "scss",
    "html",
    "json",
    "graphql",
    "md",
    "markdown",
    "mdx",
    "yaml",
    "yml",
  ],
  testMatch: [
    "**/*.js",
    "**/*.mjs",
    "**/*.jsx",
    "**/*.vue",
    "**/*.ts",
    "**/*.tsx",
    "**/*.css",
    "**/*.less",
    "**/*.scss",
    "**/*.html",
    "**/*.json",
    "**/*.graphql",
    "**/*.md",
    "**/*.markdown",
    "**/*.mdx",
    "**/*.yaml",
    "**/*.yml",
  ],
};
