name: learn-github-actions
run-name: ${{ github.actor }} is running CI/CD tests
on:
  push:
    branches: ["main"]
jobs:
  check-test-is-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.12.0"
      - run: npm install -g bats
      - run: bats -v
